### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [neffs/python-cometblue_lite#7]
It would be very helpful if you could tag releases as well again. This would enable distributions who want to fetch the source from GitHub instead of PyPI.

Thanks

**Comment by neffs** [comment]
fixed now. I also updated the home assistant integration to use the new version.

**Comment by fabaff** [comment]
There is [no tag](https://github.com/neffs/python-cometblue_lite/tags) for 0.5.2.

**Comment by neffs** [comment]
> There is [no tag](https://github.com/neffs/python-cometblue_lite/tags) for 0.5.2.

forgot to push it, sorry. Please note that 0.5.2 includes a port from bluepy to bleak. It seems to work fine, but I only did very limited testing.

**Comment by fabaff** [comment]
> Please note that 0.5.2 includes a port from bluepy to bleak. It seems to work fine, but I only did very limited testing.

Thanks for letting me know.

**Comment by fabaff** [comment]
Could you please push 0.5.3?
